### PR TITLE
Refactor parameter reading functionality

### PR DESCRIPTION
**Pull request by etcadinfinitum**
In order to simplify/streamline the code responsible for reading simulation parameters and providing the parameters to the classes being instantiated, an overhaul of the simulation's driver and relevant subclasses is needed. This PR will encompass the related issues, logged under: #249, #208, #206, possibly #187, possibly #174, possibly #135, and potentially others.

### Type of Request

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [x] Breaking change (fix or feature that would cause existing functionality to change)

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your code follow the code style of this project?
* [ ] Does your change require a change to the documentation?
* [ ] Have you updated the documentation accordingly?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Did you put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such)?

### CODE REVIEW

**Comment by etcadinfinitum** [comment]
To do:

- [x] Build `ParameterManager.h` and related implementation
- [x] Test that the correct class is instantiated based on type specified and read by `ParameterManager`
- [ ] Rebase feature branch onto master.
- [ ] Migrate `Layouts` classes to locate and initialize their own parameters; all `readParameters` implementations need to change function signature.
  * Implement `readParameters` and `printParameters` for DynamicLayout
  * Implement `readParameters` and `printParameters` for FixedLayout
- [ ] Migrate `Connections` classes to locate and initialize their own parameters; all `readParameters` implementations need to change function signature.
  * Implement `readParameters` and `printParameters` for ConnGrowth
  * Implement `readParameters` and `printParameters` for ConnStatic
- [ ] Migrate `Synapses` classes to locate and initialize their own parameters; all `readParameters` implementations need to change function signature.
  * Determine which classes need to have these signatures overloaded...
- [ ] Migrate `Neurons` classes to locate and initialize their own parameters; all `readParameters` implementations need to change function signature.
  * Determine which classes need to have these signatures overloaded
- [ ] Write tests for core modules to show that parameters are correctly read and applied to instantiated class.
- [ ] Change BGDriver so that the creation of a class and instantiation of parameters for each of the 4 modules is linear.
- [ ] Edit makefile to build with new classes and adaptations.
- [ ] Test changes with simple simulations.

**Comment by stiber** [comment]
Common operations provided by simulation entities:

- retrieveParameters()
- allocateCPUMemory()
- allocateGPUMemory()
- initializeState()
- copyToGPU()
- copyFromGPU()
- deallocateGPUMemory()
- deallocateCPUMemory()
- shutdown()

And maybe serialization/deserialization operations.

**Comment by stiber** [comment]
Also, we should switch to modifying the single-threaded-master branch.

**Comment by stiber** [comment]
Let's talk about moving this into the [SummerOfBrain](https://github.com/UWB-Biocomputing/SummerOfBrain) repo.

**Comment by etcadinfinitum** [comment]
closing this for the time being, since this work is expected to be incorporated elsewhere.

**Pull request closed without merging**
